### ISSUE TITLE
UnhandledPromiceRejectionWarning error

### ISSUE THREAD

**Issue by outlassn** [demaisj/soundcloud-rp#19]
(node:33764) UnhandledPromiseRejectionWarning: Error: child "activity" fails because [child "assets" fails because [child "small_text" fails because ["small_text" length must be at least 2 characters long]]]
    at RPCClient._onRpcMessage (C:\Users\outlassn\node_modules\discord-rpc\src\Client.js:171:19)
    at IPCTransport.emit (events.js:188:13)
    at decode (C:\Users\outlassn\node_modules\discord-rpc\src\transports\IPC.js:134:18)
    at decode (C:\Users\outlassn\node_modules\discord-rpc\src\transports\IPC.js:92:5)
    at Socket.socket.on (C:\Users\outlassn\node_modules\discord-rpc\src\transports\IPC.js:120:7)
    at Socket.emit (events.js:188:13)
    at emitReadable_ (_stream_readable.js:539:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
(node:33764) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33764) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

This decided to happen when the song changed to https://soundcloud.com/fml/th-kid-bones-youngdumbfuck-full-album

I think (?) it might have been caused due to the person's name being 1 character? (only reason I think this is because of "["small_text" length must be at least 2 characters long]]]")

**Comment by demaisj** [comment]
Hi, thanks for reporting this bug. A hotfix is on the way.
